// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmA7XtmQ3lHzeVC6_H3kwBxfk2xnCN1Lo',
    appId: '1:303691086090:web:b7109b85e74321f138e2f3',
    messagingSenderId: '303691086090',
    projectId: 'socialapp-d1e32',
    authDomain: 'socialapp-d1e32.firebaseapp.com',
    storageBucket: 'socialapp-d1e32.appspot.com',
    measurementId: 'G-JQ8LFRX739',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_c_H0oDH_dKC6-VMSNhZgIIhVVlMou4I',
    appId: '1:303691086090:android:0265288ce89598d138e2f3',
    messagingSenderId: '303691086090',
    projectId: 'socialapp-d1e32',
    storageBucket: 'socialapp-d1e32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsXoaeoIMVpbsqIJMBqOK85koOj2UdkA',
    appId: '1:303691086090:ios:04cf82f5cc80df1038e2f3',
    messagingSenderId: '303691086090',
    projectId: 'socialapp-d1e32',
    storageBucket: 'socialapp-d1e32.appspot.com',
    iosClientId: '303691086090-fcefmfh3bifga10t5q44eqnt47k9co72.apps.googleusercontent.com',
    iosBundleId: 'com.example.sports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXsXoaeoIMVpbsqIJMBqOK85koOj2UdkA',
    appId: '1:303691086090:ios:4d4b7bf571221f5538e2f3',
    messagingSenderId: '303691086090',
    projectId: 'socialapp-d1e32',
    storageBucket: 'socialapp-d1e32.appspot.com',
    iosClientId: '303691086090-om4647lh56g6nv1ubbtdvj2qilho9u2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sports.RunnerTests',
  );
}
